#pragma once

/*
class BaseActor
{
public:
    BaseActor();
    virtual ~BaseActor();

    virtual void Update();
};
*/

struct BaseActor;

void BaseActorConstructor(BaseActor* self); // BaseActor()

// ~BaseActor()
// if Destructor is declared as virtual, Compiler implicitly generates Destructor to call ChildDestructor from Vptr
// Implicitly Generated at compiler time
void BaseActorDestructor(BaseActor* self);

void BaseActorVirtualDestructor(BaseActor* self); // virtual ~BaseActor()
void BaseActorVirtualUpdate(BaseActor* self); // virtual void Update

// Methods implicitly generated for this class to look up the right method in virtual table and call it
void BaseActorUpdate(BaseActor* self);
//

// Each class has its own virtual table
struct BaseActorVtable
{
    // only used or generated by compiler when this class or parent's Destructor is declared as virtual
    void (*ChildDestructor)(void* self);
    void (*Update)(BaseActor* self);
};

struct BaseActor
{
    const void* Vptr;
    bool HasVirtualDestructor;
};