#pragma once
#include "Character.h"

/*
class Player : public Character
{
public:
    Player();
    Player(float AttackDamage);
    ~Player();

    void Attack() override;
*/

struct Player;
void PlayerConstructor(Player* self); // Player()
void PlayerConstructor(Player* self, float AttackDamage); // Player(float AttackDamage)
void PlayerDestructor(Player* self); // ~Player()

// Methods implicitly generated for this class to look up the right method in virtual table and call it
void PlayerUpdate(Player* self);
void PlayerAttack(Player* self);
//

// Each class has its own virtual table
struct PlayerVtable
{
    // only used or generated by compiler when Destructor is declared as virtual
    void (*ChildDestructor)(void* self);
    void (*Update)(Character* self);
    void (*Attack)(Character* self);
};

struct Player
{
    // Inherited from Base class
    Character Parent;
};