#pragma once
#include "Character.h"

struct Player;
void PlayerConstructor(Player* self); // Player()
void PlayerConstructor(Player* self, float AttackDamage); // Player(float AttackDamage)
void PlayerDestructor(Player* self); // ~Player()

// Methods generated by this class to run Virtual Methods derived from Parent Class
void PlayerUpdate(Player* self);
void PlayerAttack(Player* self);
//

// Each class has its own virtual table
struct PlayerVtable
{
    // only used or generated by compiler when Destructor is declared as virtual
    void (*ChildDestructor)(void* self);
    void (*Update)(Character* self);
    void (*Attack)(Character* self);
};

struct Player
{
    // Inherited from Base class
    Character Parent;
};